add batch tally contracts

diff --git a/impl/scripts/find_clang b/impl/scripts/find_clang
--- a/impl/scripts/find_clang
+++ b/impl/scripts/find_clang
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# An utility script used to find a binary of clang 16+
+# An utility script used to find a binary of clang 17+
 
 if [[ -n "${CLANG}" ]]; then
   echo "${CLANG}"
@@ -12,11 +12,14 @@ fi
 # at the end.
 SEARCH_TARGET="${SEARCH_TARGET:-llvm-strip}"
 
-CANDIDATES=("${SEARCH_TARGET}-19" "${SEARCH_TARGET}-20" "${SEARCH_TARGET}-21")
+CANDIDATES=("${SEARCH_TARGET}-17" "${SEARCH_TARGET}-18" "${SEARCH_TARGET}-19" "${SEARCH_TARGET}-20" "${SEARCH_TARGET}-21")
 
 BREW_PREFIX=$(brew --prefix 2> /dev/null)
 if [[ -n "${BREW_PREFIX}" ]]; then
   CANDIDATES+=(
+    "${BREW_PREFIX}/opt/llvm/bin/${SEARCH_TARGET}"
+    "${BREW_PREFIX}/opt/llvm@17/bin/${SEARCH_TARGET}"
+    "${BREW_PREFIX}/opt/llvm@18/bin/${SEARCH_TARGET}"
     "${BREW_PREFIX}/opt/llvm@19/bin/${SEARCH_TARGET}"
     "${BREW_PREFIX}/opt/llvm@20/bin/${SEARCH_TARGET}"
     "${BREW_PREFIX}/opt/llvm@21/bin/${SEARCH_TARGET}"
@@ -26,11 +29,11 @@ fi
 for candidate in ${CANDIDATES[@]}; do
   OUTPUT=$($candidate --version 2> /dev/null | grep 'version [0-9]' | head -n 1 | cut -d'.' -f 1 | grep -o '[0-9][0-9]*')
 
-  if [[ $((OUTPUT)) -ge 19 ]]; then
+  if [[ $((OUTPUT)) -ge 17 ]]; then
     echo "${candidate/${SEARCH_TARGET}/clang}"
     exit 0
   fi
 done
 
->&2 echo "Cannot find clang of version 19+!"
+>&2 echo "Cannot find clang of version 17+!"
 exit 1
